version: '3.1'

services:

  db:
    env_file:
      - db/db.env
    volumes:
      - db:/data/db

  api:
    image: strapi/strapi
    env_file:
      - api/api.env
    environment:
      NODE_ENV: development
    command: yarn develop
    volumes:
      - ./api/src:/srv/app
      - /srv/app/node_modules
      - /srv/app/.cache
      - /srv/app/build

  thumbor:
    ports:
      - "8000:8000"
    env_file:
      - thumbor/thumbor.env
    volumes:
      - thumbor:/data
      - media:/media
      - media_cache:/tmp/media_cache
      - ./thumbor/thumbor.conf.tpl:/usr/src/app/thumbor.conf.tpl

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - logs:/logs

  web:
    env_file:
      - web/web.env
    environment:
      NODE_ENV: development
    command: yarn wait-dev
    volumes:
      - ./web/src:/srv/app
      - /srv/app/node_modules
      - /srv/app/.next

  mongo_express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=thedbusername
      - ME_CONFIG_MONGODB_ADMINPASSWORD=thedbpassword
    depends_on:
      - db
    links:
      - db
    ports:
      - 3002:8081
    networks:
      - xstack
