version: '3.1'

services:

  db:
    image: mongo:4
    command: --quiet
    networks:
      - travels

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: ghcr.io/timboslicecreative/travels/api
    ports:
      - 1337:1337
    depends_on:
      - db
    networks:
      - travels

  thumbor:
    image: apsl/thumbor:latest
    ports:
      - "8000:8000"
    networks:
      - travels

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ghcr.io/timboslicecreative/travels/nginx
    depends_on:
      - thumbor
    ports:
      - 3001:80
    networks:
      - travels

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    image: ghcr.io/timboslicecreative/travels/web
    ports:
      - 3000:3000
    depends_on:
      - api
      - nginx
    networks:
      - travels

networks:
  travels:
    driver: bridge

volumes:
  db: {}
  thumbor: {}
  logs: {}